### ISSUE TITLE
Draft of Thai subtitles

### ISSUE THREAD

**Issue by bact** [iliasbartolini/the-internet-s-own-boy--aaron-swartz--subtitles#14]
[internets-own-boy-th-20170909-srt.txt](https://github.com/iliasbartolini/the-internet-s-own-boy--aaron-swartz--subtitles/files/1588925/internets-own-boy-th-20170909-srt.txt)

Most of the work is by students at Media Arts and Design program, Chiang Mai University. First screening on December 2015.

Typo fixing, editing, correcting some translation, and resyncing later by me. There are still some glitches to be fixed.

Released to public domain.

Hopefully will find way to put some of these to Amara at 
https://amara.org/en/videos/5Mo4oAj1bxOb/info/the-internets-own-boy-the-story-of-aaron-swartz/

**Comment by iliasbartolini** [comment]
Thank you for your contribution! 
Very appreciated, I added it to the repository.
