### ISSUE TITLE
Please add Ukrainian language on Transifex

### ISSUE THREAD

**Issue by yurkobb** [iliasbartolini/the-internet-s-own-boy--aaron-swartz--subtitles#17]
I would like to translate the subtitles into Ukrainian, but it is not available on Transifex. I have sent an add language request - please confirm it, @iliasbartolini.

**Comment by iliasbartolini** [comment]
Should be enable now! 
Thanks for reaching out and helping with the translations.
Feel free to make a PR here when the translation is complete.

**Comment by yurkobb** [comment]
Hm, still not in the list, maybe there is a delay...

![Знімок екрана з 2019-11-12 01-45-52](https://user-images.githubusercontent.com/479389/68629986-c2c20480-04dd-11ea-8640-641fec57306f.png)

**Comment by iliasbartolini** [comment]
Check again please .... PEBKAC

**Comment by yurkobb** [comment]
It is there now! Thanks!
